In [212]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA,TruncatedSVD
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Ridge,Lasso,BayesianRidge
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,mean_absolute_error
import math

# TESTING THE ACCURACY BY APPLYING LINEAR REGRESSION WITHOUT ANY DATA WRANGLING

In [196]:
df=pd.read_csv("OnlineNewsPopularity.csv")

In [197]:
df.head()

,url,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,http://mashable.com/2013/01/07/amazon-instant-...,731.0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,http://mashable.com/2013/01/07/ap-samsung-spon...,731.0,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,http://mashable.com/2013/01/07/apple-40-billio...,731.0,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,http://mashable.com/2013/01/07/astronaut-notre...,731.0,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,http://mashable.com/2013/01/07/att-u-verse-apps/,731.0,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505

In [198]:
df.describe()

,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
count,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,...,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000
mean,354.530471,10.398749,546.514731,0.548216,0.996469,0.689175,10.883690,3.293638,4.544143,1.249874,...,0.095446,0.756728,-0.259524,-0.521944,-0.107500,0.282353,0.071425,0.341843,0.156064,3395.380184
std,214.163767,2.114037,471.107508,3.520708,5.231231,3.264816,11.332017,3.855141,8.309434,4.107855,...,0.071315,0.247786,0.127726,0.290290,0.095373,0.324247,0.265450,0.188791,0.226294,11626.950749
min,8.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,1.000000
25%,164.000000,9.000000,246.000000,0.470870,1.000000,0.625739,4.000000,1.000000,1.000000,0.000000,...,0.050000,0.600000,-0.328383,-0.700000,-0.125000,0.000000,0.000000,0.166667,0.000000,946.000000
50%,339.000000,10.000000,409.000000,0.539226,1.000000,0.690476,8.000000,3.000000,1.000000,0.000000,...,0.100000,0.800000,-0.253333,-0.500000,-0.100000,0.150000,0.000000,0.500000,0.000000,1400.000000
75%,542.000000,12.000000,716.000000,0.608696,1.000000,0.754630,14.000000,4.000000,4.000000,1.000000,...,0.100000,1.000000,-0.186905,-0.300000,-0.050000,0.500000,0.150000,0.500000,0.250000,2800.000000
max,731.000000,23.000000,8474.000000,701.000000,1042.000000,650.000000,304.000000,116.000000,128.000000,91.000000,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.500000,1.000000,843300.000000

In [199]:
df.isnull().sum()

url                             0
timedelta                       0
n_tokens_title                  0
n_tokens_content                0
n_unique_tokens                 0
                               ..
title_subjectivity              0
title_sentiment_polarity        0
abs_title_subjectivity          0
abs_title_sentiment_polarity    0
shares                          0
Length: 61, dtype: int64

In [200]:
arr=np.array(df)

In [201]:
x=arr[:,2:60]
x

array([[12.0, 219.0, 0.663594466988, ..., -0.1875, 0.0, 0.1875],
       [9.0, 255.0, 0.604743080614, ..., 0.0, 0.5, 0.0],
       [9.0, 211.0, 0.575129530699, ..., 0.0, 0.5, 0.0],
       ...,
       [10.0, 442.0, 0.5163551389800001, ..., 0.13636363636399998,
        0.0454545454545, 0.13636363636399998],
       [6.0, 682.0, 0.5394932927880001, ..., 0.0, 0.5, 0.0],
       [10.0, 157.0, 0.7019867503180001, ..., 0.25, 0.166666666667, 0.25]],
      dtype=object)

In [202]:
y=arr[:,60]

In [203]:

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=20)

In [204]:
print(xtrain.shape)
print(ytrain.shape)

(27750, 58)
(27750,)

In [205]:

lr=LinearRegression()
lr.fit(xtrain,ytrain)
xpred=lr.predict(xtrain)
xpred=np.array(xpred)
lr.score(xtest,ytest)

0.02637061368501925

In [206]:
xpred=lr.predict(xtest)

In [207]:

print(math.sqrt(mean_squared_error(ytest,xpred)))

7276.261726498578

## --------------------------------------------------------------------------------------------------------
# Data Extraction and Wrangling from here

In [208]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
numerical = ['n_tokens_title', 'n_tokens_content', 'num_hrefs', 'num_self_hrefs', 'num_imgs','num_videos',
            'average_token_length','num_keywords','self_reference_min_shares','self_reference_max_shares',
             'self_reference_avg_sharess']

In [209]:
df1=df
df1[numerical]=scaler.fit_transform(df[numerical])

In [210]:
df1.head()

,url,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,http://mashable.com/2013/01/07/amazon-instant-...,731.0,0.476190,0.025844,0.663594,1.0,0.815385,0.013158,0.017241,0.007812,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,http://mashable.com/2013/01/07/ap-samsung-spon...,731.0,0.333333,0.030092,0.604743,1.0,0.791946,0.009868,0.008621,0.007812,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,http://mashable.com/2013/01/07/apple-40-billio...,731.0,0.333333,0.024900,0.575130,1.0,0.663866,0.009868,0.008621,0.007812,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,http://mashable.com/2013/01/07/astronaut-notre...,731.0,0.333333,0.062662,0.503788,1.0,0.665635,0.029605,0.000000,0.007812,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,http://mashable.com/2013/01/07/att-u-verse-apps/,731.0,0.523810,0.126505,0.415646,1.0,0.540890,0.062500,0.163793,0.156250,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505

In [211]:
y11=df1['shares']
df1=df1.drop(['url','timedelta','shares'],axis=1)

In [213]:
svd=TruncatedSVD(n_components=10)
arr=svd.fit_transform(df1)
arr=pd.DataFrame(arr)
df12=pd.concat([df1,arr],axis=1)
df12=scaler.fit_transform(df12)

In [214]:
x11train,x11test,y11train,y11test=train_test_split(df1,y11,test_size=0.3)

In [215]:
predictions=np.zeros((y11test.shape))

# MODEL FITTING

In [216]:
bay_rid=BayesianRidge()
bay_rid.fit(x11train,y11train)
bay_pred=bay_rid.predict(x11test)
predictions+=bay_pred

In [217]:
lass=Lasso()
lass.fit(x11train,y11train)
lass_pred=lass.predict(x11test)
predictions+=lass_pred

In [218]:
ridge=Ridge(alpha=0.5)
ridge.fit(x11train,y11train)
predictions+=ridge.predict(x11test)

In [219]:
lin_reg=LinearRegression()
lin_reg.fit(x11train,y11train)
predictions+=lin_reg.predict(x11test)

In [220]:
predictions/=4

# RESULTS

In [221]:
print("Root mean squared error : %f"%math.sqrt(mean_squared_error(y11test,predictions)))
print("Mean absolute error : %f"%(mean_absolute_error(y11test,predictions)))

Root mean squared error : 12256.624594
Mean absolute error : 3016.665505